### ISSUE TITLE
Tutoriales Hortonworks

### ISSUE THREAD

**Issue by alvarag** [Josemi/TFG#4]
Tutoriales a seguir de Hortonworks:
- Introducción/Instalación: https://es.hortonworks.com/tutorial/learning-the-ropes-of-the-hortonworks-sandbox/
- Una vez esté todo instalado y funcionando en Gamma, tan sólo es ir siguiendo los manuales: el 2, 3...

**Comment by Josemi** [comment]
HDP, HDF y Proxy instalados correctamente en Gamma
