### ISSUE TITLE
Primeros pasos en el VPN

### ISSUE THREAD

**Issue by Josemi** [Josemi/TFG#5]
Acceder al VPN de la universidad con la cuenta que se me ha proporcionado y cambiar la contraseña.

**Comment by Josemi** [comment]
Me han surgido algunos problemas al conectarme a la VPN.

**Comment by jmaudes** [comment]
tienes que instalarte primero FortiClient
https://www.ubu.es/servicio-de-informatica-y-comunicaciones/ayuda-y-documentacion/ayuda-y-documentacion-de-usuario/manuales-vpn

**Comment by Josemi** [comment]
He instalado FortiClient y con la ayuda de Alvar he conseguido conectarme al VPN desde la universidad y desde FortiClient (desde fuera de la universidad).
